### ISSUE TITLE
[Proposal] nearup configure

### ISSUE THREAD

**Issue by chefsale** [near/nearup#155]
I'm working on adding a new command:

```
nearup configure
```

which would support the following options for now:
```
nearup configure systemd=true
# or
nearup configure systemd=false # which would be the default behaviour as it is now
```
which will enable users to configure if they want use the current watcher implementation or they could use systemd as the supervisor. 
```
nearup run testnet
```

also the configure command would allow to make the node archival or non archival, current defualt behaviour is non archival and people have to manually change the ~/.near/<network>/config.json.
This command would enable them to change it through nearup with:
```
nearup configure archival=true
# or 
nearup configure archival=false # which is the current default behaviour
```

also this would generate a ~/.nearup/config.json file in which we could store additional information which nearup is using:
```
 {
    "chain_id": "testnet",
    "systemd": true,
    etc...
 }
```
so you wouldn't have to specify the chain_id in the run command, but instead you would be able to configure it and just use:
```
nearup configure chain=testnet
nearup configure archival=true
nearup configure systemd=ture
nearup run
``` 
For example.

In the future I plan to add more things like:
```
nearup configure canary=true
``` 

which would always run master instead of running the deployed version, etc.

cc: @bowenwang1996 @ngmiller @mhalambek

**Comment by nickmonad** [comment]
Is it true that to use systemd, one has to run as root? Shouldn't there be an ability for regular users to spin up their own services that start when the login?

**Comment by chefsale** [comment]
Thats true we can make it a user service.

**Comment by bowenwang1996** [comment]
@frol what do you think

**Comment by frol** [comment]
Well, I see a mix of options here; let me go one at a time.

> `nearup configure systemd=true`

1. It is not common to see syntax like `systemd=true` in *nix CLIs. I won't go into details since (2)
2. I don't think you want to have `systemd=true/false`, `supervisord=true/false`, `naive-watcher=true/false` since we don't want to have several supervisors at the same time.  Thus, I propose `nearup configure --set-supervisor=systemd`

> `nearup run testnet`

Does it imply that you can seemlesly run `nearup run mainnet` right there and have two nodes running at the same time? Is this `testnet` an alias or chain id? How would it look for guildnet, for example? Do we need to hard-code every possible network into the code?

I would prefer to have `nearup start` to mimic common UX of supervisors with start/stop/status commands. My intuition about `run` command is that it runs the binary right here without a supervisor (basically, I would expect we configure supervisor to use `nearup run` to exec the process)

> `nearup configure archival=true`

1. Same comment about `=true` (`--enable-archival-mode` / `--disable-archival-mode`)
2. It should also ask for the tracking shards

> ```
> nearup configure --set-chain=testnet
> nearup configure --enable-archival-mode
> nearup configure --set-supervisor=systemd
> nearup start
> ```

I think we should be able to configure `--home` folder for the config, so developers may easily run `nearup --home ~/.nearup/mainnet-test-migration run` to spin up the node with the config (that also means that `configure` should also respect the `--home` argument, and it should also have a way to configure neard home folder).

```
nearup --home ~/.nearup/mainnet-test-migration configure --set-chain=mainnet
# by default nearup may just use `~/.near/<chain-id>`
nearup --home ~/.nearup/mainnet-test-migration configure --set-neard-home=~/.near/mainnet-test-migration
nearup --home ~/.nearup/mainnet-test-migration configure --enable-archival-mode
nearup --home ~/.nearup/mainnet-test-migration configure --set-supervisor=systemd
nearup --home ~/.nearup/mainnet-test-migration start
```
