### ISSUE TITLE
`nearup` doesn't read `RUST_LOG` from environment

### ISSUE THREAD

**Issue by pmnoxx** [near/nearup#193]
We have an option to specify `RUST_LOG` when running `nearup`. 

However, it's highly not intuitive.
```shell
nearup run --neard-log <LOG_LEVEL> mainnet
```

While, people expect it to work like this as well:
```shell
RUST_LOG=ERROR nearup run mainnet
```
See https://github.com/near/nearcore/issues/5826#issuecomment-995305120

**Comment by mina86** [comment]
I believe this is fixed. `nearup` does not touch `RUST_LOG` environment variable unless either `--neard-log` or `--verbose` flag is passed. I believe the observed behaviour was not because of `nearup` but because `neard` was in a habit of overriding `RUST_LOG`. This has been addressed in https://github.com/near/nearcore/issues/6008
