### ISSUE TITLE
Start command should auto-populate the configs / genesis / ...

### ISSUE THREAD

**Issue by frol** [near/nearup#4]
Currently, when I run from scratch, I bump into:

```
$ nearup betanet --nodocker --binary-path ./target/debug/
Using local binary at ./target/debug/
Missing files node_key.json, validator_key.json, config.json, genesis.json in /home/frol/.near/. Maybe last init was failed. either specify different --home or remove /home/frol/.near/ to start from scratch.
```

**Comment by ailisp** [comment]
This is a intended check. Because if your last `near init` panic, `near init`/`near run` would give confusing error message (this just because ~/.near in an incomplete state, usually only two keys are generated, but not config or genesis). It doesn't try to delete and recreate because it's also possible you want to keep keys. What is in your ~/.near?

**Comment by frol** [comment]
My `~/.near` folder contained the subfolders from `pytest`ing. Well, the behavior you describe makes sense.

I had removed the `~/.near` folder and the script worked out fine!
