### ISSUE TITLE
localnet unexpected behavior

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearup#47]
For developers who transition to using nearup, `nearup localnet` behavior is different from `scripts/start_localnet.py`, which can cause a lot of confusions.

**Comment by ailisp** [comment]
@mfornet do you have time to take a look? If not, I can add missing parts next week.

**Comment by ailisp** [comment]
Work on this today

**Comment by ailisp** [comment]
run a docker testnet is done in #52 Other than that start_localnet features are all exist:
```
    parser.add_argument('--local', action='store_true', help='deprecated: use --nodocker')
    parser.add_argument('--nodocker', action='store_true', help='If set, compiles and runs the node on the machine directly (not inside the docker).')
    parser.add_argument('--debug', action='store_true', help='If set, compiles local nearcore in debug mode')
    parser.add_argument('--verbose', action='store_true', help='If set, prints verbose logs')
    parser.add_argument('--home', default=os.path.expanduser('~/.near/'), help='Home path for storing configs, keys and chain data (Default: ~/.near)')
    parser.add_argument(
        '--image', default='nearprotocol/nearcore',
        help='Image to run in docker (default: nearprotocol/nearcore)')
```

Note the original design of localnet by @mfornet  is a more poweful, allow you launch multiple localnet nodes, so it's also have to be different (to take args of number of nodes, validators) from start_localnet.py, Since start_localnet.py is covered by nearup, I suggest we abandon start_localnet.py from now
