### ISSUE TITLE
Specify what needs to be compiled for --nodocker

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearup#7]
Running --nodocker should provide information which binaries to compile (ideally the command to do it).
```
nearup betanet --nodocker --binary-path=target/release/
Using local binary at target/release/
Warning: current deployed version on betanet is 2e5f367c3c08f07ea673ea25b856a83463ac3959, but local binary is 6d07a2d40. It might not work
Setting up network configuration.
Enter your account ID (leave empty if not going to be a validator):
Generating node key...
Traceback (most recent call last):
  File "/Users/cypress/.nearup/main.py", line 64, in <module>
    verbose=args.verbose)
  File "/Users/cypress/.nearup/nearuplib/nodelib.py", line 318, in setup_and_run
    home_dir, init_flags, no_gas_price)
  File "/Users/cypress/.nearup/nearuplib/nodelib.py", line 118, in check_and_setup
    nodocker_init_official(chain_id, binary_path, home_dir, account_id)
  File "/Users/cypress/.nearup/nearuplib/nodelib.py", line 38, in nodocker_init_official
    account_id, False)
  File "/Users/cypress/.nearup/nearuplib/nodelib.py", line 413, in initialize_keys
    generate_node_key(home, binary_path, nodocker, image)
  File "/Users/cypress/.nearup/nearuplib/nodelib.py", line 362, in generate_node_key
    subprocess.call(cmd)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'target/release//keypair-generator': 'target/release//keypair-generator'
```

**Comment by ailisp** [comment]
I made nearcore's makefile to compile necessary binary `make release` and `make debug`. (i should document this) Practically this should not be an issue because nearup users could be:
1) use precompiled binary or docker (this works)
2) want to compile themselves
For 2) they would follow our instructions to clone repo and build. There we can document them to do a `make release`. And since they choose 2 to build themselves, they're considered as "power user" or "developer with reasonabe knowledge", so we can expect they follow the build instruction.

There is long term plan nearup would also clone nearcore at ~/.nearup/nearcore, and manage compilation process for user, but it add little benefit for us (slow, we probably have the built binary somewhere) and more work to maintain git and cargo, so I keep it simple to unblock automate betanet release

**Comment by ilblackdragon** [comment]
You can still specify which binaries should be compiled.

Currently it says `please compile nearcore locally and set --binary-path`, but nearcore is repository not a binary. What needs to be compiled is `cargo build -p near && cargo build -p keypair-generator` with --release.

**Comment by frol** [comment]
FYI, You can specify two binaries in a single cargo build command

**Comment by ailisp** [comment]
In README it documents people need to `make release` before giving the binary-path: https://github.com/near/nearup#start-devnet-betanet-testnet-with-local-nearcore

**Comment by ailisp** [comment]
Also changed the cmdline hint to:
```
Sorry your Operating System does not have officially compiled binary now.
Please compile locally by `make debug` or `make release` in nearcore and set --binary-path
```

**Comment by ailisp** [comment]
Close as it gives what command to run now
