### ISSUE TITLE
Following directions under install section returns undesirable results.

### ISSUE THREAD

**Issue by mikedotexe** [near/nearup#87]
Reported from the community. I went into a temporary directory and pasted the install command:
`curl --proto '=https' --tlsv1.2 -sSfL https://up.near.dev | python3` and get

>nearup: error: the following arguments are required: command

We'll want to update the readme.

<img width="754" alt="Screenshot 2020-07-28 16 29 14" src="https://user-images.githubusercontent.com/1042667/88739492-86781800-d0ef-11ea-8037-34b7e7b50682.png">

Bo, I tagged you because I believe you work on this the most, but feel free to tag another person. I did not see a CODEOWNERS file in this repo so I tagged you. Thanks

**Comment by ailisp** [comment]
This is expected and introduced in https://github.com/near/nearup/pull/77 in order to work around rainbow-bridge CLI. It's safe to ignore this error but I agree it's annoying to see `error: the following arguments are required: command` at the initial installation. @chefsale Do you have a good idea to fix this? Maybe in rainbow bridge cli first check nearup is installed? Or in nearup doesn't show error message if it's invoked by `curl ... | python3`? Both sounds hacky, WDYT

**Comment by jjangg96** [comment]
In Dockerfile, doesn't let RUN that command because of error. When build Dockerfile all command must have no error.

**Comment by ailisp** [comment]
@jjangg96 as a work around you can do:
```
RUN curl --proto '=https' --tlsv1.2 -sSfL https://up.near.dev | python3 || true
```
in dockerfile for now

**Comment by chefsale** [comment]
We have a new way of running it, as we are working on rewrite and this should be merged into master on 5th of October. Follow these docs: https://github.com/near/nearup/tree/nearup_v2
